# Generated by Django 4.2.9 on 2024-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_author_category_comment_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
